// ----------------user details -----------
export const GET_CUSTOMERS_TABLE_DATA = 'GET_CUSTOMERS_TABLE_DATA';
export const GET_CUSTOMERS_TABLE_DATA_SUCCESS = 'GET_CUSTOMERS_TABLE_DATA_SUCCESS';
export const GET_CUSTOMERS_TABLE_DATA_FAIL = 'GET_CUSTOMERS_TABLE_DATA_FAIL';
export const UPDATE_CUSTOMER_SWITCH = 'UPDATE_CUSTOMER_SWITCH';

// --------------- company details -----------
// export const GET_COMPANYDETAILS_DATA = 'GET_COMPANYDETAILS_DATA';
// export const GET_COMPANYDETAILS_DATA_SUCCESS = 'GET_COMPANYDETAILS_DATA_SUCCESS';
// export const GET_COMPANYDETAILS_DATA_FAIL = 'GET_COMPANYDETAILS_DATA_FAIL';