// ----------------Customers  -----------
export const GET_CUSTOMERS_TABLE_DATA = 'GET_CUSTOMERS_TABLE_DATA';
export const GET_CUSTOMERS_TABLE_DATA_SUCCESS = 'GET_CUSTOMERS_TABLE_DATA_SUCCESS';
export const GET_CUSTOMERS_TABLE_DATA_FAIL = 'GET_CUSTOMERS_TABLE_DATA_FAIL';
export const UPDATE_CUSTOMER_SWITCH = 'UPDATE_CUSTOMER_SWITCH';

// ----------------Customers  -----------
export const GET_VENDORS_TABLE_DATA = 'GET_VENDORS_TABLE_DATA';
export const GET_VENDORS_TABLE_DATA_SUCCESS = 'GET_VENDORS_TABLE_DATA_SUCCESS';
export const GET_VENDORS_TABLE_DATA_FAIL = 'GET_VENDORS_TABLE_DATA_FAIL';
export const UPDATE_VENDOR_SWITCH = 'UPDATE_VENDOR_SWITCH';