// ----------------user details -----------
export const GET_USERS_TABLE_DATA = 'GET_USERS_TABLE_DATA';
export const GET_USERS_TABLE_DATA_SUCCESS = 'GET_USERS_TABLE_DATA_SUCCESS';
export const GET_USERS_TABLE_DATA_FAIL = 'GET_USERS_TABLE_DATA_FAIL';
export const UPDATE_USER_SWITCH = 'UPDATE_USER_SWITCH';

// --------------- company details -----------
export const GET_COMPANYDETAILS_DATA = 'GET_COMPANYDETAILS_DATA';
export const GET_COMPANYDETAILS_DATA_SUCCESS = 'GET_COMPANYDETAILS_DATA_SUCCESS';
export const GET_COMPANYDETAILS_DATA_FAIL = 'GET_COMPANYDETAILS_DATA_FAIL';