
export const GET_USERS_TABLE_DATA = 'GET_USERS_TABLE_DATA';
export const GET_USERS_TABLE_DATA_SUCCESS = 'GET_USERS_TABLE_DATA_SUCCESS';
export const GET_USERS_TABLE_DATA_FAIL = 'GET_USERS_TABLE_DATA_FAIL';
export const UPDATE_USER_SWITCH = 'UPDATE_USER_SWITCH';
