export const GET_FCL_SURCHARGE_TABLE_DATA = 'GET_FCL_SURCHARGE_TABLE_DATA';
export const GET_FCL_SURCHARGE_TABLE_DATA_SUCCESS = 'GET_FCL_SURCHARGE_TABLE_DATA_SUCCESS';
export const GET_FCL_SURCHARGE_TABLE_DATA_FAIL = 'GET_FCL_SURCHARGE_TABLE_DATA_FAIL';