export const UPDATE_QUOTE_MODAL_CHARGES = "UPDATE_QUOTE_MODAL_CHARGES";
export const GET_CURRENCY_EXCHANGE_RATE = "GET_CURRENCY_EXCHANGE_RATE";
export const GET_CURRENCY_EXCHANGE_RATE_SUCCESS = "GET_CURRENCY_EXCHANGE_RATE_SUCCESS";