export const GET_FCL_TABLE_DATA = 'GET_FCL_TABLE_DATA';
export const GET_FCL_TABLE_DATA_SUCCESS = 'GET_FCL_TABLE_DATA_SUCCESS';
export const GET_FCL_TABLE_DATA_FAIL = 'GET_FCL_TABLE_DATA_FAIL';
export const UPDATE_FCL_TABLE_DATA = 'UPDATE_FCL_TABLE_DATA';