export const GET_FCL_TABLE_DATA = 'GET_FCL_TABLE_DATA';
export const GET_FCL_TABLE_DATA_SUCCESS = 'GET_FCL_TABLE_DATA_SUCCESS';
export const GET_FCL_TABLE_DATA_FAIL = 'GET_FCL_TABLE_DATA_FAIL';
export const UPDATE_FCL_TABLE_DATA = 'UPDATE_FCL_TABLE_DATA';
export const UPDATE_FCL_SWITCH = 'UPDATE_FCL_SWITCH';
export const FILTER_FCL_DATA = 'FILTER_FCL_DATA';
export const ADD_FCL_DATA = 'ADD_FCL_DATA';
export const UPDATE_FCL_ACTIVE_TAB = 'UPDATE_FCL_ACTIVE_TAB';
export const UPDATE_INLAND_ACTIVE_TAB = 'UPDATE_INLAND_ACTIVE_TAB';

export const GET_LCL_TABLE_DATA = 'GET_LCL_TABLE_DATA';
export const GET_LCL_TABLE_DATA_SUCCESS = 'GET_LCL_TABLE_DATA_SUCCESS';
export const GET_LCL_TABLE_DATA_FAIL = 'GET_LCL_TABLE_DATA_FAIL';
export const UPDATE_LCL_SWITCH = 'UPDATE_LCL_SWITCH';

// procurement/ocean freight/port local charges
export const GET_PORTLOCALCHARGES_TABLE_DATA = 'GET_PORTLOCALCHARGES_TABLE_DATA';
export const GET_PORTLOCALCHARGES_TABLE_DATA_SUCCESS = 'GET_PORTLOCALCHARGES_TABLE_DATA_SUCCESS';
export const GET_PORTLOCALCHARGES_TABLE_DATA_FAIL = 'GET_PORTLOCALCHARGES_TABLE_DATA_FAIL';
export const FILTER_PORTLOCALCHARGES_DATA = 'FILTER_PORTLOCALCHARGES_DATA';
//-----------------------------------

export const GET_WAYBILL_TABLE_DATA = 'GET_WAYBILL_TABLE_DATA';
export const GET_WAYBILL_TABLE_DATA_SUCCESS = 'GET_WAYBILL_TABLE_DATA_SUCCESS';
export const GET_WAYBILL_TABLE_DATA_FAIL = 'GET_WAYBILL_TABLE_DATA_FAIL';
export const UPDATE_AIRWAYBILL_SWITCH = 'UPDATE_AIRWAYBILL_SWITCH';
export const ADD_AIRWAYBILL_DATA = 'ADD_AIRWAYBILL_DATA';

export const GET_CONSOLE_TABLE_DATA = 'GET_CONSOLE_TABLE_DATA';
export const GET_CONSOLE_TABLE_DATA_SUCCESS = 'GET_CONSOLE_TABLE_DATA_SUCCESS';
export const GET_CONSOLE_TABLE_DATA_FAIL = 'GET_CONSOLE_TABLE_DATA_FAIL';
export const UPDATE_AIRCONSOLE_SWITCH = 'UPDATE_AIRCONSOLE_SWITCH';

export const GET_INLAND_TABLE_DATA = 'GET_INLAND_TABLE_DATA';
export const GET_INLAND_TABLE_DATA_SUCCESS = 'GET_INLAND_TABLE_DATA_SUCCESS';
export const GET_INLAND_TABLE_DATA_FAIL = 'GET_INLAND_TABLE_DATA_FAIL';
export const UPDATE_INLAND_SWITCH = 'UPDATE_INLAND_SWITCH';
export const ADD_INLAND_DATA = 'ADD_INLAND_DATA';

export const UPDATE_CARRIER_DATA = 'UPDATE_CARRIER_DATA';
export const BLANK_CARRIER_DATA = 'BLANK_CARRIER_DATA';

// ------------------------- 
export const UPLOAD_FCL_CARRIER_DATA = 'UPLOAD_FCL_CARRIER_DATA';
export const UPLOAD_FCL_FREIGHT = 'UPLOAD_FCL_FREIGHT';
export const UPLOAD_FCL_SURCHARGE = 'UPLOAD_FCL_SURCHARGE';