export const GET_VENDOR_DETAILS = 'GET_VENDOR_DETAILS'
export const GET_VENDOR_DETAILS_SUCCESS = 'GET_VENDOR_DETAILS_SUCCESS'

export const GET_CURRENCY_DETAIL = 'GET_CURRENCY_DETAIL'
export const GET_CURRENCY_DETAIL_SUCCESS = 'GET_CURRENCY_DETAIL_SUCCESS'

export const GET_UOM_DATA = 'GET_UOM_DATA'
export const GET_UOM_DATA_SUCCESS = 'GET_UOM_DATA_SUCCESS'

export const GET_SURCHARGE_CODE_DATA = 'GET_SURCHARGE_CODE_DATA'
export const GET_SURCHARGE_CODE_DATA_SUCCESS = 'GET_SURCHARGE_CODE_DATA_SUCCESS'

export const GET_SURCHARGE_CATEGORY_DATA = 'GET_SURCHARGE_CATEGORY_DATA'
export const GET_SURCHARGE_CATEGORY_DATA_SUCCESS = 'GET_SURCHARGE_CATEGORY_DATA_SUCCESS'

export const GET_OCEAEN_PORT_DATA = 'GET_OCEAEN_PORT_DATA'
export const GET_OCEAEN_PORT_DATA_SUCCEESS = 'GET_OCEAEN_PORT_DATA_SUCCEESS'