export const GET_VENDOR_DETAILS = 'GET_VENDOR_DETAILS'
export const GET_VENDOR_DETAILS_SUCCESS = 'GET_VENDOR_DETAILS_SUCCESS'

export const GET_CURRENCY_DETAIL = 'GET_CURRENCY_DETAIL'
export const GET_CURRENCY_DETAIL_SUCCESS = 'GET_CURRENCY_DETAIL_SUCCESS'