export const GET_PARTIES_CUSTOMER_DETAILS_TYPE = "GET_PARTIES_CUSTOMER_DETAILS_TYPE";
export const GET_PARTIES_CUSTOMER_DETAILS_TYPE_SUCCESS = "GET_PARTIES_CUSTOMER_DETAILS_TYPE_SUCCESS";


export const UPLOAD_CUSTOMER_COMPANYDATA_TYPE = "UPLOAD_CUSTOMER_COMPANYDATA_TYPE";
export const UPLOAD_CUSTOMER_CONTACT_TYPE = "UPLOAD_CUSTOMER_CONTACT_TYPE";
export const UPLOAD_CUSTOMER_DOCUMENT_TYPE = "UPLOAD_CUSTOMER_DOCUMENT_TYPE";

export const GET_CUSTOMERS_ID = "GET_CUSTOMERS_ID";