v# This workflow will build and push the SPA application to GCS bucket when code change is committed.

name: Deploy SPA app to GCP Cloud Storage bucket

on:
  push:
    branches: [ "master" ]
  pull_request:
#    types: [opened, synchronize, reopened, closed]
    branches: [ "master" ]

# Environment variables available to all jobs and steps in this workflow
env:
  APP_LOCATION: "/" # location of your client code
  API_LOCATION: "api" # location of your api source code - optional
  APP_ARTIFACT_LOCATION: "build" # location of client code build output
  # GCP config details
  GCP_PROJECT_ID: "tarifftales-website"
  GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }} 
  GCP_SA_KEY: ${{ secrets.GCP_SA_PRIVATE_KEY }} 

# permissions:
#  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: 'actions/checkout@v3'

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ env.GCP_SA_EMAIL }}
        service_account_key: ${{ env.GCP_SA_KEY }}
        project_id: ${{ env.GCP_PROJECT_ID }}

    - uses: 'actions/setup-node@v3'
      with:
        node-version: '18.x'

#    - name: 'npm build'
#      run: ' npm install google-maps-react --legacy-peer-deps && npm run build'


      
