# This workflow will build and push the SPA application to GCS bucket when code change is committed.

name: Deploy SPA app to GCP Cloud Storage bucket

on:
  push:
    branches: [ "master" ]
  pull_request:
#    types: [opened, synchronize, reopened, closed]
    branches: [ "master" ]

# Environment variables available to all jobs and steps in this workflow
env:
  APP_LOCATION: "/" # location of your client code
  API_LOCATION: "api" # location of your api source code - optional
  APP_ARTIFACT_LOCATION: "build" # location of client code build output
  # GCP config details
  GCP_SA_JSON: ${{secrets.GCP_SA_JSON}}

# permissions:
#  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: 'actions/checkout@v3'

    # Setup gcloud CLI
    - id: 'auth'
      name: 'gCloud authentication'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ env.GCP_SA_JSON }}'

    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up gCloud'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'gcloud info'
      run: 'gcloud info'

    - name: 'Setup Node'
      uses: 'actions/setup-node@v3'
      with:
        node-version: '18.x'

    - name: 'npm build'
      run: ' npm install google-maps-react --legacy-peer-deps && npm run build && ls -lrta ./build'

    - id: 'upload-files'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'build'
        destination: 'tarifftales-spa-app'
        parent: false
        
    - id: 'publish'
      run: 'echo ${{ steps.upload-files.outputs.uploaded }}'

      
