export const UPDATE_INSTANT_RATE_SWAP = 'UPDATE_INSTANT_RATE_SWAP'
export const UPDATE_VALUE_BLANK = 'UPDATE_VALUE_BLANK'
export const UPDATE_SEARCH_INSTANT_RATE_DATA = 'UPDATE_SEARCH_INSTANT_RATE_DATA'
export const UPDATE_SEARCH_INSTANT_RATE_DATE = 'UPDATE_SEARCH_INSTANT_RATE_DATE'


export const ADD_OBJECT_INSTANT_SEARCH = 'ADD_OBJECT_INSTANT_SEARCH'
export const REMOVE_OBJECT_INSTANT_SEARCH = 'REMOVE_OBJECT_INSTANT_SEARCH'