export const UPDATE_INSTANT_RATE_SWAP = 'UPDATE_INSTANT_RATE_SWAP'
export const UPDATE_VALUE_BLANK = 'UPDATE_VALUE_BLANK'
export const UPDATE_SEARCH_INSTANT_RATE_DATA = 'UPDATE_SEARCH_INSTANT_RATE_DATA'