export const UPDATE_INSTANT_RATE_SWAP = 'UPDATE_INSTANT_RATE_SWAP'
export const UPDATE_VALUE_BLANK = 'UPDATE_VALUE_BLANK'
export const UPDATE_SEARCH_INSTANT_RATE_DATA = 'UPDATE_SEARCH_INSTANT_RATE_DATA'
export const UPDATE_SEARCH_INSTANT_RATE_DATE = 'UPDATE_SEARCH_INSTANT_RATE_DATE'
export const UPDATE_SHIPMENT_DETAILS_CONFIRM = 'UPDATE_SHIPMENT_DETAILS_CONFIRM'
export const UPDATE_CONTAINER_TYPE_CONFIRM = 'UPDATE_CONTAINER_TYPE_CONFIRM'
export const UPDATE_CONTAINER_CHANGE = 'UPDATE_CONTAINER_CHANGE'


export const ADD_OBJECT_INSTANT_SEARCH = 'ADD_OBJECT_INSTANT_SEARCH'
export const REMOVE_OBJECT_INSTANT_SEARCH = 'REMOVE_OBJECT_INSTANT_SEARCH'